=== sermo-de-arboribus/2022-NaNoGenMo/src/main/resources/quotes-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  jaxb:version="2.1"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
  <xs:element name="quotes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="quote"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="quote">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="version"/>
        <xs:element ref="author" maxOccurs="5"/>
      </xs:sequence>
      <xs:attribute name="genre" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="diary" />
            <xs:enumeration value="drama" />
            <xs:enumeration value="information-technology" />
            <xs:enumeration value="culture-studies" />
            <xs:enumeration value="letters" />
            <xs:enumeration value="linguistics"/>
            <xs:enumeration value="philosophy" />
            <xs:enumeration value="poetry" />
            <xs:enumeration value="politics-and-society" />
            <xs:enumeration value="psychology" />
            <xs:enumeration value="science" />
            <xs:enumeration value="fiction" />
            <xs:enumeration value="travelogue" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="version">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="text"/>
        <xs:element ref="source"/>
      </xs:sequence>
      <xs:attribute name="status" use="required">
        <xs:simpleType>
          <xs:list>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="original" />
                <xs:enumeration value="translation" />
                <xs:enumeration value="unpublished" />
              </xs:restriction>
            </xs:simpleType>
          </xs:list>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="lang" use="required">
        <xs:simpleType>
          <xs:annotation>
            <xs:appinfo>
              <jaxb:javaType name="java.util.Locale"
                parseMethod="de.sda.quotes.model.LocaleParser.parseXmlLangAttribute" 
                printMethod="de.sda.quotes.model.LocaleParser.printXmlLangAttribute"/>
            </xs:appinfo>
          </xs:annotation>
          <xs:restriction base="xs:string">
            <xs:pattern value="\w{2,3}(-\w{2,3})?" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="public-domain" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:maxInclusive value="3000"/>
            <xs:minInclusive value="1867"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="em" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="source">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="idref" minOccurs="0"/>
        <xs:element ref="page" minOccurs="0"/>
        <xs:element ref="translator" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="idref" type="xs:integer"/>
  <xs:element name="page">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="([-0-9/]+)|(check)|([IVXLMC]+)"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="author" type="xs:string"/>
  <xs:element name="translator" type="xs:string"/>
</xs:schema>

=== sermo-de-arboribus/2022-NaNoGenMo/config/public-domain-quotes.xml
<?xml version="1.0" encoding="UTF-8"?>
<quotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="quotes-schema.xsd">
   <quote genre="psychology">
      <version status="original" lang="en-AT" public-domain="2008">
            <text>People often believe that left and right are contradictions, that man and woman, hot and cold, light and heavy, strong and weak are contradictions. From a scientific standpoint, they are not contradictions, but varieties. They are degrees of a scale, arranged in accordance with their approximation to some ideal fiction. In the same way, good and bad, normal and abnormal, are not contradictions but varieties. Any theory which treats sleep and waking, dream thoughts and day thoughts, as contradictions is bound to be unscientific.</text>
            <source>
                <title>What Life Should Mean to You</title>
                <page>60</page>
            </source>
        </version>
      <author>Adler, Alfred</author>
   </quote>
   <quote genre="philosophy">
      <version status="original" lang="grc" public-domain="1867">
            <text>Κάλλιστον τὸ δικαιότατον, λῷστον δ' ὑγιαίνειν ἤδιστον δὲ πέφυχ' οὗ τις ἐρᾷ τὸ τυχεῖν.</text>
            <source>
                <title>Δηλιακὸν ἐπίγραμα</title>
            </source>
        </version>
      <version status="translation" lang="de-DE" public-domain="2002">
            <text>Das Schönste ist die Gerechtigkeit, das Beste Gesundsein. Aber das Süßeste ist, wenn man erlangt, was man liebt.</text>
            <source>
                <title>Delisches Epigramm</title>
                <translator>Rolfes, Eugen</translator>
            </source>
        </version>
      <author>Anonym, nach Aristoteles</author>
   </quote>
   <quote genre="poetry">
      <version status="original" lang="fr-FR" public-domain="1989">
            <text>
Ne sois pas lascif et peureux
Comme le lièvre et l'amoureux.
Mais que toujours ton cerveau soit
La hase pleine qui conçoit.</text>
            <source>
                <title>Poetische Werke</title>
                <page>24</page>
            </source>
        </version>
      <author>Apollinaire, Guillaume</author>
   </quote>
   <quote genre="">
      <version status="original" lang="grc" public-domain="1867">
            <text>φιλοῦνται δὲ σχεδὸν μάλιστα οἱ ἐλευθέριοι τῶν ἀπ᾽ ἀρετῆς· ὠφέλιμοι γὰρ, τοῦτο δ᾽ ἐν τῇ δόσει.</text>
            <source>
                <title>Ηθικά Νικομάχεια</title>
            </source>
        </version>
      <version status="translation" lang="de-DE" public-domain="2002">
            <text>Liebe aber und Freundschaft gewinnt kaum einer durch eine Tugend so sehr wie der Freigebige, da er sich nützlich erweist. Das geschieht aber durch Geben.</text>
            <source>
                <title>Nikomachische Ethik</title>
                <idref>100</idref>
                <translator>Rolfes, Eugen</translator>
            </source>
        </version>
      <author>Aristoteles</author>
   </quote>
   <quote genre="">
      <version status="original" lang="grc" public-domain="1867">
            <text>οὐ γὰρ ἐπαινεῖται ὁ φοβούμενος οὐδὲ ὁ ὀργιζόμενος, οὐδὲ ψέγεται ὁ ἁπλῶς ὀργιζόμενος ἀλλ᾽ ὁ πῶς</text>
            <source>
                <title>Ηθικά Νικομάχεια</title>
                <page>1106</page>
            </source>
        </version>
      <version status="translation" lang="de-DE" public-domain="2002">
            <text>[...] denn man wird nicht gelobt, wenn man sich fürchtet oder wenn man zornig wird, und nicht getadelt, wenn man einfach zornig wird, sondern wenn es auf bestimmte Weise geschieht.</text>
            <source>
                <title>Nikomachische Ethik</title>
                <idref>100</idref>
                <translator>Rolfes, Eugen</translator>
            </source>
        </version>
      <author>Aristoteles</author>
   </quote>
   <quote genre="">
      <version status="original" lang="grc" public-domain="1867">
            <text>τῷ δὲ φευκτὸν ἢ οὐ σπουδαστὸν τὸ ἐπαρκεῖν, μοχθηρῷ ὄντι· εὖ πάσχειν γὰρ οἱ πολλοὶ βούλονται, τὸ δὲ ποιεῖν φεύγουσιν ὡς ἀλυσιτελές.</text>
            <source>
                <title>Ηθικά Νικομάχεια</title>
                <page>1163</page>
            </source>
        </version>
      <version status="translation" lang="de-DE" public-domain="2022">
            <text>Denn Gutes empfangen wollen alle, aber Gutes zu tun hütet man sich, weil es nichts einbringt.</text>
            <source>
                <title>Nikomachische Ethik</title>
                <idref>100</idref>
                <translator>Rolfes, Eugen</translator>
            </source>
        </version>
      <author>Aristoteles</author>
   </quote>
   <quote genre="">
      <version status="original" lang="grc" public-domain="1867">
            <text>ὥσπερ γὰρ καὶ τελεωθὲν βέλτιστον τῶν ζῴων ὁ ἄνθρωπός ἐστιν, οὕτω καὶ χωρισθεὶς νόμου καὶ δίκης χείριστον πάντων.</text>
            <source>
                <title>Πολιτικά</title>
                <page>1253</page>
            </source>
        </version>
      <version status="translation" lang="de-DE" public-domain="2002">
            <text>Denn wie der Mensch in seiner Vollendung das vornehmste Geschöpf ist, so ist er auch, des Gesetzes und Rechtes ledig, das schlechteste von allen.</text>
            <source>
                <title>Politik</title>
                <idref>101</idref>
                <translator>Rolfes, Eugen</translator>
            </source>
        </version>
      <version status="translation" lang="en-GB" public-domain="1867">
            <text>[F]or as by the completion of it man is the most excellent of all living beings, so without law and justice he would be the worst of all</text>
            <source>
                <title>A Treatise on Government</title>
                <translator>Ellis, William</translator>
            </source>
        </version>
      <author>Aristoteles</author>
   </quote>
   <quote genre="">
      <version status="original" lang="de-DE" public-domain="1867">
            <text>Faul bin ich übrigens wie die Sünde und habe mir ordentlich instinktmäßig ein kleines Blat genommen, um nicht zu viel zu schreiben.</text>
            <source>
                <title>Brief an Clemens Brentano, Juli 1812, zit. n. Arnim / Brentano: Freundschaftsbriefe.</title>
                <idref>106</idref>
            </source>
        </version>
      <version status="unpublished" lang="en-DE" public-domain="1867">
            <text>Incidentally I'm as lazy as sin and instinctively I took a properly small sheet, not to write too much.</text>
            <source>
                <title>Letter to Clemens Brentano, July 1812</title>
                <translator>Weber, Kai</translator>
            </source>
        </version>
      <author>Arnim, Achim von</author>
   </quote>
   <quote genre="">
      <version status="original" lang="de-DE" public-domain="1867">
            <text>„Wie kann ein Wohlthäter der Menschen, mit der höchsten Weisheit und Gnade begabt, solch ein Saumatz seyn!“ seufzte Frau Hildegard. Aber Berthold, der viel in Römern und Griechen gelesen hatte, suchte ihr deutlich zu machen, wie gerade die allgemeine, wissenschaftliche Ansicht, wenn sie allein herrschend würde, die sittlichen Grenzen des einzelnen Menschen auslösche; er sehe so Mannigfaltiges, Widersprechendes geglaubt und geehrt, daß er nur den Geist achte, in welchem alles getrieben würde. Frau Hildegard schüttelte mit dem Kopfe und warnte Berthold gegen die Bücher, daß er es nicht auch einmal so treibe wie Faust, wenn er ganz gesund würde.</text>
            <source>
                <title>Die Kronenwächter</title>
                <page>613</page>
            </source>
        </version>
      <version status="unpublished" lang="en-DE" public-domain="1867">
            <text>"How can a benefactor of mankind, blessed with the highest wisdom and grace, be such a vile creep!", Mrs. Hildegard sighed. But Berthold, who had read lots of the Romans and Greeks, tried to make it clear to her, how the general scientific opinion, when it becomes the sole ruler of discourse, is particularly capable of erasing the moral boundaries of the individual; he could see such diverse and contradictory things believed and honoured, that he only respected the mind which drives it all. Mrs. Hildegard shook her head and warned Berthold of the books, and asked him, when once he would be fully reovered, not to go as far as Faust did.</text>
            <source>
                <title>The Guardians of the Crown</title>
                <translator>Weber, Kai</translator>
            </source>
        </version>
      <author>Arnim, Achim von</author>
   </quote>
   <quote genre="">
      <version status="original" lang="fr-FR" public-domain="2019">
            <text>Il n'y a de vide dans la nature que, d'après nous, à un moment ou à un autre, l'esprit humain ne peut remplir</text>
            <source>
                <title>Manifests pour un théâtre avorté</title>
            </source>
        </version>
      <author>Artaud, Antonin</author>
   </quote>
   <quote genre="">
      <version status="original" lang="fr-FR" public-domain="1960">
            <text>Mais je me figure que l'enfer, vu par un soupirail, devrait être plus effrayant que si, d'un seul et planant regard, on pouvait l'embrasser tout entier.</text>
            <source>
                <title>Le dessous de cartes d'une partie de whist, en: Les Diaboliques</title>
            </source>
        </version>
      <version status="translation" lang="de-DE" public-domain="2000">
            <text>Ich bildete mir ein: Die Hölle, mit einem Male überschaut, kann lange nicht so grässlich sein wie ein Einblick in sie, getan durch ein Kellerloch.</text>
            <source>
                <title>Hinter den Karten, in: Die Teuflischen</title>
                <translator>Schurig, Arthur</translator>
            </source>
